language: ruby
matrix:
  include:
    - rvm: 2.3.0
      env: REDMINE_VERSION=3.2.0
    - rvm: 2.2.4
      env: REDMINE_VERSION=3.2.0
    - rvm: 2.1.8
      env: REDMINE_VERSION=3.2.0
    - rvm: 2.0.0
      env: REDMINE_VERSION=3.2.0
    - rvm: 2.2.4
      env: REDMINE_VERSION=3.1.3
    - rvm: 2.1.8
      env: REDMINE_VERSION=3.1.3
    - rvm: 2.0.0
      env: REDMINE_VERSION=3.1.3
before_install: bash -x bin/travisci_before_install.sh
before_script: bash -x bin/travisci_before_script.sh
script: bash -x bin/travisci_exec_test.sh
after_script: bash -x  bin/travisci_after_script.sh
