language: ruby
matrix:
  include:
    - rvm: 2.3.1
      env: REDMINE_VERSION=3.2.2
    - rvm: 2.2.5
      env: REDMINE_VERSION=3.2.2
    - rvm: 2.1.8
      env: REDMINE_VERSION=3.2.2
    - rvm: 2.0.0
      env: REDMINE_VERSION=3.2.2
    - rvm: 2.2.5
      env: REDMINE_VERSION=3.1.5
    - rvm: 2.1.8
      env: REDMINE_VERSION=3.1.5
    - rvm: 2.0.0
      env: REDMINE_VERSION=3.1.5
before_install: bash -x bin/travisci_before_install.sh
before_script: bash -x bin/travisci_before_script.sh
script: bash -x bin/travisci_exec_test.sh
