language: ruby
matrix:
  include:
    - rvm: 2.2.3
      env: REDMINE_VERSION=3.2.0
    - rvm: 2.1.7
      env: REDMINE_VERSION=3.2.0
    - rvm: 2.0.0
      env: REDMINE_VERSION=3.2.0
    - rvm: 2.2.3
      env: REDMINE_VERSION=3.1.1
    - rvm: 2.1.7
      env: REDMINE_VERSION=3.1.1
    - rvm: 2.0.0
      env: REDMINE_VERSION=3.1.1
before_install: bash -x bin/travisci_before_install.sh
before_script: bash -x bin/travisci_before_script.sh
script: bash -x bin/travisci_exec_test.sh
